# This is a basic workflow to help you get started with Actions

name: build gh-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildpush:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      APP_DOMAIN: "construction.jujiyangasli.com"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2

      - name: setup
        run: yarn

      - name: export
        run: |
          yarn build
          yarn export

          ls -la out

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: "construction.jujiyangasli.com"
